### ISSUE TITLE
Add support for AMD GPU with ROCm

### ISSUE THREAD

**Issue by japrogramer** [Zyphra/Zonos#81]
Both pytorch and mamba can run on AMD through HIP (Heterogeneous-compute Interface for Portability) from the ROCm (Radeon Open Compute) ecosystem.

so there is no reason to not be able to run Zonos on AMD GPUs

**Comment by japrogramer** [comment]
https://github.com/Zyphra/Zonos/issues/47#issuecomment-2660378257

**Comment by japrogramer** [comment]
both  pytorch and mamba look like they are ready to go to run on AMD
``` pytorch
https://pytorch.org/docs/stable/notes/hip.html
https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/3rd-party/pytorch-install.html#
```

``` mamba
https://github.com/state-spaces/mamba/blob/main/setup.py#L142
```

**Comment by brcisna** [comment]
What fails on this with AMD GPU is the flash-attn, mamba-ssm , and causal-conv1d fails due to the way the setup parses with pytorch version being used . There is an explanation for this on AMD ROCm site the difference between Nvidia and AMD GPU version parsing.
I messed with for many hours last couple days tring to get these three packages to compile,,,, but tehy all three bomb due to version parsing.

This is on Debian 13 trixie, testing. in an Python3.10 venv 
Have a AMD Radeon Pro W6600,,,which will work with these with the HSA_OVERIDE gfx1030 override 

Thanks

**Comment by japrogramer** [comment]
@brcisna what ROCm version are you using ?

all three libraries report working with ROCm 6.1 and above.

**Comment by brcisna** [comment]
ROCm 6.2
After serveral build attempts pretty certain is that all of the clang stuff for ROCm is built with older versions of GCC GCC++ than what Debian 13 has. Even in a venv stuff is being used with default system gcc gcc++ to compile. If you try and install for exampe mamba-ssm binary you can force install it,, but the scan_module will not import correctly.
Pretty certain if i run up a VM of Debian 12 with the older gcc version this would work ZONOS 
(I have to have debian 13 Trixie for cellular modems,to work correctly ,,for example )
Still trying

**Comment by AwesomeApple12** [comment]
> ROCm 6.2 After serveral build attempts pretty certain is that all of the clang stuff for ROCm is built with older versions of GCC GCC++ than what Debian 13 has. Even in a venv stuff is being used with default system gcc gcc++ to compile. If you try and install for exampe mamba-ssm binary you can force install it,, but the selective_scan_module will not import correctly. Also if i run python setup.py install the mamba-ssm from source,with the HSA_OVERIDE=10.3.0 it compiles for quite a while im not sure this adapter maybe not letting mamba-ssm comile correctly also.. but exits with.
> 
> `selective_scan_fwd_fp32.hip:(.text+0x130): multiple definition of `__low2float(__hip_bfloat162)'; /home/superuser/MyPrograms/zonos/Zonos/mamba/build/temp.linux-x86_64-cpython-310/csrc/selective_scan/selective_scan_bwd_bf16_complex.o:selective_scan_bwd_bf16_complex.hip:(.text+0x130): first defined here collect2: error: ld returned 1 exit status error: command '/usr/bin/g++' failed with exit code 1 ` ..really no errors shown at all just exits?
> 
> Pretty certain if i run up a VM of Debian 12 with the older gcc version this would work ZONOS with ROCm HIP (I have to have debian 13 Trixie for cellular modems,to work correctly ,,for example ) Also worth noting the docker installation blew chunks bigtime,,I sort of figured that before i even tried it.
> 
> Still trying

ROCm works best with ubuntu 22.04/Linux Mint Edge 21.3, you can try to use Ubuntu 24.04, but face some issues. Try one of those.

**Comment by billbeans** [comment]
after running the `uv sync --extra compile` step it says that it can't find ROCm, even though I have it in /opt/.  i installed uv with pipx, could this be why? using Debian 12

**Comment by brcisna** [comment]
@billbeans 

Not trying to sound smart,,,but you'll never get flash-attn to build with PyTorch-ROCm ,HIP  on any version of Debian.
Have spent hours to try and make it compile.
Even pulling down the official Pytorch_ROCm docker image which is native Ubuntu based the build fails,
It could be my GPU also,,, Radeon Pro W6600 = gfx1032 
Also tried setting the ARCHS= variable to known working AMD GPU's and flash-attn always fails.

**Comment by billbeans** [comment]
> but still uses CPU
When I try running the sample, it aborts at about 5%

**Comment by brcisna** [comment]
@billbeans 

Only trying to help.  If you ever want to give it a go,,,and have Anydesk on you Linux box,,,Id be glad to set up youe vev for Zonos.
Ive monkeyed with Linux for 35 years,,,,still dont squat about it,,,but i could surely get your Zonos setup...
Are you doing Ubuntu or Debian?

BTW I am using a lowly Radeon Pro W6600 

Just an idea....

**Comment by billbeans** [comment]
@brcisna 
I am using Debian 12 with a Radeon RX 6600 which uses RDNA2. I installed [this package](https://github.com/supersonictw/navicl) a while back to get ROCm working, since AMD does not officially support Debian. I know it works because I was able to use Davinci Resolve, hashcat, and a few other pieces of software successfully now. I also have `export HSA_OVERRIDE_GFX_VERSION=10.3.0` in my ~/.profile as per the advice of the navicl dev I linked above.

I've been using Linux for around 2 years now, I still have a lot to learn... Don't have Anydesk, but it looks like it's basically an RDP application, which has many FOSS alternatives

**Comment by brcisna** [comment]
@billbeans

 just doa  search for Install Anydesk on Linux.
You end up with a 9 digit remote access number.
If you dont want someone to log into you machine I get it,,
Just trying to help.
It would take 45 minutes but you would have   a working zonos,,,,, 
Sounds like youve done most of the setup,,,,if Davnci is recognozing your 6600.
I just like figuring this stuff out,,,,im retired,,,, ha ha..
Im on Debian Trixie,,,and even though Ubuntu is a spin off of Debian,,,there are many differences,,,,when setting stuff like this up....

**Comment by japrogramer** [comment]
This might still be helpful 

https://github.com/state-spaces/mamba/issues/671#issuecomment-2679537079

**Comment by YellowRoseCx** [comment]
Flash-attn only works on RX 7000 series GPUs and newer, the solution for me was to build mamba in editable mode and then down the 2 rotary files from flash-attention's repo, place them in the mamba project and change the imports for RotaryEmbedding to the new files and change the import location of triton.rotary to the new location too
like this: ``from mamba_ssm.modules.rotary import RotaryEmbedding``

I'm still working on getting everything dialed in, but I should be able to upload my fork and write a full install guide once I do. I'm on an RX 6800xt

As of now, the Transformer backend works as is though

**Comment by YellowRoseCx** [comment]
> [@YellowRoseCx](https://github.com/YellowRoseCx)
> 
> Am going to try and do a build per the link [@japrogramer](https://github.com/japrogramer) linked above. I am using an Radeon Pro W6600 = gfx1032,,,, but i do an export = gfx1030 which should be the equivilant of your GPU you built against. Am curious to see if i can get a successful build. Like you said,, was pretty sure the build process was only looking for cuda,,and not for cuda_ROCm. Ill report in next couple days...

That's just for using the hybrid model though. You can use the transformer model

**Comment by YellowRoseCx** [comment]
I documented how to install Zonos using AMD GPUs and how to use FlashAttention2 with them https://github.com/YellowRoseCx/Zonos-ROCm?tab=readme-ov-file#installation
